config/routes.rb
Rails.application.routes.draw do
  get 'homepage/show'
  get 'profile/:id', to: 'profile#show', as: :profile
  get 'search', to: 'search#index'
  get 'search/find_by_recipe', to: 'search#find_by_recipe', as: :search_find_by_recipe
  get 'search/find_by_tag', to: 'search#find_by_tag', as: :search_find_by_tag
  get 'search/find_by_user', to: 'search#find_by_user', as: :search_find_by_user
  resources :masterpieces
  resources :recipes
  resources :collections
  devise_for :users
  post '/recipes/:id/like', to: 'recipes#like', as: :recipe_like
  post '/recipes/:id/unlike', to: 'recipes#unlike', as: :recipe_unlike
  post '/recipes/:id/bookmark', to: 'recipes#bookmark', as: :recipe_bookmark
  post '/recipes/:id/unbookmark', to: 'recipes#unbookmark', as: :recipe_unbookmark
  post '/masterpieces/:id/like', to: 'masterpieces#like', as: :masterpiece_like
  post '/masterpieces/:id/unlike', to: 'masterpieces#unlike', as: :masterpiece_unlike
  root 'homepage#show'

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_server_error'
  get 'errors/security_transgression_error', as: :security_transgression_error

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :collection_recipes
  has_many :recipes, through: :collection_recipes, source: :recipe
  has_many :user_bookmark_collections
  has_many :users_bookmarking_it, through: :user_bookmark_collections, source: :user

  validates :name, presence: true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:user_id, :name, :description)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= simple_form_for(@collection) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :creator %>
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Collections</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.creator %></td>
        <td><%= collection.name %></td>
        <td><%= collection.description %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @collection.creator %>
</p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @collection.description %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>