config/routes.rb
Rails.application.routes.draw do
  get 'homepage/show'
  get 'profile/:id', to: 'profile#show', as: :profile
  get 'search', to: 'search#index'
  get 'search/find_by_recipe', to: 'search#find_by_recipe', as: :search_find_by_recipe
  get 'search/find_by_tag', to: 'search#find_by_tag', as: :search_find_by_tag
  get 'search/find_by_user', to: 'search#find_by_user', as: :search_find_by_user
  resources :masterpieces
  resources :recipes
  resources :collections
  devise_for :users
  post '/recipes/:id/like', to: 'recipes#like', as: :recipe_like
  post '/recipes/:id/unlike', to: 'recipes#unlike', as: :recipe_unlike
  post '/recipes/:id/bookmark', to: 'recipes#bookmark', as: :recipe_bookmark
  post '/recipes/:id/unbookmark', to: 'recipes#unbookmark', as: :recipe_unbookmark
  post '/masterpieces/:id/like', to: 'masterpieces#like', as: :masterpiece_like
  post '/masterpieces/:id/unlike', to: 'masterpieces#unlike', as: :masterpiece_unlike
  root 'homepage#show'

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_server_error'
  get 'errors/security_transgression_error', as: :security_transgression_error

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

def index
end

def find_by_recipe
  @keyword = params[:search]
  if @keyword == ''
    @recipes = Recipe.none
  else
    @recipes_array = Recipe.find_by_sql(["
    SELECT recipes_with_keyword.* ,
       COALESCE( like.cnt, 0 ) AS users_liking_it_count,
       COALESCE( bookmark.cnt, 0 ) AS users_bookmarking_it_count,
       COALESCE( cook.cnt, 0 ) AS cooks_count
    FROM (
      SELECT * FROM
      recipes
      WHERE title LIKE ? OR description LIKE ?
      ORDER BY created_at DESC
    ) AS recipes_with_keyword
    LEFT JOIN
      ( SELECT recipe_id, COUNT(*) AS cnt FROM
        user_like_recipes
        GROUP BY recipe_id ) AS like
    ON recipes_with_keyword.id = like.recipe_id
    LEFT JOIN
      ( SELECT recipe_id, COUNT(*) AS cnt FROM
        user_bookmark_recipes
        GROUP BY recipe_id ) AS bookmark
    ON recipes_with_keyword.id = bookmark.recipe_id
    LEFT JOIN
      ( SELECT recipe_id, COUNT(*) AS cnt FROM
        masterpieces
        GROUP BY recipe_id ) AS cook
    ON recipes_with_keyword.id = cook.recipe_id
    ", "%"+@keyword+"%", "%"+@keyword+"%"])

    @recipes = Kaminari.paginate_array(@recipes_array).page(params[:page]).per(20)

    ActiveRecord::Associations::Preloader.new.preload(@recipes, :tags)
    ActiveRecord::Associations::Preloader.new.preload(@recipes, :creator)
  end
end

def find_by_tag
  @keyword = params[:search]
  if @keyword == ''
    @recipes = Recipe.none
  else
    @tag_id = ActsAsTaggableOn::Tag.find_by_sql(["
    SELECT tags.id FROM tags WHERE (LOWER(name) = LOWER(?))
    ", @keyword])

    # @tag.blank?
    @recipes_array = Recipe.find_by_sql(["
    SELECT recipes_with_tag.* ,
       COALESCE( like.cnt, 0 ) AS users_liking_it_count,
       COALESCE( bookmark.cnt, 0 ) AS users_bookmarking_it_count,
       COALESCE( cook.cnt, 0 ) AS cooks_count
    FROM (
      SELECT * FROM
      recipes
      JOIN taggings ON taggings.taggable_id = recipes.id
      AND taggings.taggable_type = 'Recipe'
      AND taggings.tag_id = ?
    ) AS recipes_with_tag
    LEFT JOIN
      ( SELECT recipe_id, COUNT(*) AS cnt FROM
        user_like_recipes
        GROUP BY recipe_id ) AS like
    ON recipes_with_tag.id = like.recipe_id
    LEFT JOIN
      ( SELECT recipe_id, COUNT(*) AS cnt FROM
        user_bookmark_recipes
        GROUP BY recipe_id ) AS bookmark
    ON recipes_with_tag.id = bookmark.recipe_id
    LEFT JOIN
      ( SELECT recipe_id, COUNT(*) AS cnt FROM
        masterpieces
        GROUP BY recipe_id ) AS cook
    ON recipes_with_tag.id = cook.recipe_id
    ", @tag_id])

    @recipes = Kaminari.paginate_array(@recipes_array).page(params[:page]).per(20)

    ActiveRecord::Associations::Preloader.new.preload(@recipes, :tags)
    ActiveRecord::Associations::Preloader.new.preload(@recipes, :creator)
  end
end

def find_by_user
  @keyword = params[:search]
  if @keyword == ''
    @users = User.none
  else
    @users = User.search(params[:search]).order("email ASC").page(params[:page]).per(20)
  end
end


end

app/helpers/search_helper.rb
module SearchHelper
  def cache_key_for_search_recipe_snippet(recipe)
    "recipe-#{recipe.id}-#{recipe.updated_at.try(:utc).try(:to_s,:number)}-#{recipe.users_liking_it.count}-#{recipe.users_bookmarking_it.count}-#{recipe.cooks.count}"
  end
  def cache_key_for_search_user_snippet(user)
    "user-#{user.id}-#{user.updated_at.try(:utc).try(:to_s,:number)}"
  end
end

app/views/search/_recipe_image.html.erb
<%= image_tag recipe.recipe_img.url(:square), class: "media-object"%>

app/views/search/_recipe_snippet.html.erb
<h4 class="media-heading"><span class="recipe-link"><%= link_to recipe.title.truncate(40, separator: ' '), recipe %></span></h4>
<div><%= recipe.description.truncate(80, separator: ' ') %></div>
<span class="glyphicon glyphicon-heart"></span> <b><%= recipe.users_liking_it_count %></b> |
<span class="glyphicon glyphicon-bookmark"></span> <b><%= recipe.users_bookmarking_it_count %></b> |
<span class="glyphicon glyphicon-cutlery"></span> <b><%= recipe.cooks_count %></b>
<div>
<% recipe.tags.each do |tag| %>
<span class="tag-link"><%= link_to tag.name, search_find_by_tag_path(search: tag.name), class: "btn btn-custom light-gray" %></span>
<% end %>
</div>

<div>created by: <span class="user-link"><%= link_to recipe.creator.username, profile_path(recipe.creator) %></span></div>

app/views/search/_search_bar.html.erb
<div class="row">
  <div class="col-md-6">
    <ul class="nav nav-pills">
      <li <%= raw 'class="active"' if type == 'recipe' %>><a href="#pill1" data-toggle="tab">Recipe</a></li>
      <li <%= raw 'class="active"' if type == 'tag' %>><a href="#pill2" data-toggle="tab">Tag</a></li>
      <li <%= raw 'class="active"' if type == 'user' %>><a href="#pill3" data-toggle="tab">User</a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane fade <%= 'in active' if  type == 'recipe' %>" id="pill1">
        <%= form_tag(search_find_by_recipe_path, method: "get", class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag :search, nil, class: "form-control", placeholder: "Search recipe by name", style: "min-width: 200px"  %>
          <%= submit_tag "Search", class: 'form-control' %>
        </div>
        <% end %>
      </div>
      <div class="tab-pane fade <%= 'in active' if  type == 'tag' %>" id="pill2">
        <%= form_tag(search_find_by_tag_path, method: "get", class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag :search, nil, class: "form-control", placeholder: "Search recipe by tag", style: "min-width: 200px"  %>
          <%= submit_tag "Search", class: 'form-control' %>
        </div>
        <% end %>
      </div>
      <div class="tab-pane fade <%= 'in active' if  type == 'user' %>" id="pill3">
        <%= form_tag(search_find_by_user_path, method: "get", class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag :search, nil, class: "form-control", placeholder: "Search user", style: "min-width: 200px"  %>
          <%= submit_tag "Search", class: 'form-control' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search/_search_result_table.html.erb
<div class="row">
  <ul class="media-list">
    <% items.each do |item| %>
    <li class="media col-md-6">
      <a class="pull-left" href="#">
        <% if type == 'recipe' %>
        <%= render partial: 'recipe_image', locals: {recipe: item} %>
        <% elsif type == 'user' %>
        <%= render partial: 'user_image', locals: {user: item} %>
        <% end %>
      </a>
      <div class="media-body">
        <% if type == 'recipe' %>
        <%= render partial: 'recipe_snippet', locals: {recipe: item} %>
        <% elsif type == 'user' %>
        <%= render partial: 'user_snippet', locals: {user: item} %>
        <% end %>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/search/_user_image.html.erb
<%= image_tag user.avatar.url(:square), class: "media-object"%>

app/views/search/_user_snippet.html.erb
<% cache(cache_key_for_search_user_snippet(user)) do %>
<h4 class="media-heading"><span class="user-link"><%= link_to user.username, profile_path(user) %></span></h4>
<div>Email: <%= user.email %></div>
<div>Joined since <%= user.created_at.strftime("%b %d, %Y") %></div>
<% end %>

app/views/search/find_by_recipe.html.erb
<%= render partial: 'search_bar', locals: {type: 'recipe'} %>
<div clas="row">
  <div class="col-md-12">
    <h2>Recipe Search Result: <b>"<%= @keyword %>"</b></h2>
  </div>
  <hr class="medium" />
</div>
<%= render partial: 'search_result_table', locals: {items: @recipes, type: 'recipe'} %>
<!-- Begin Pagination -->
<div class="pagination-container text-center">
  <div class="row">
    <div class="col-md-12">
      <ul class="pagination pagination-sm works-pagination">
        <%= paginate @recipes %>
      </ul>
    </div>
  </div>
</div>
<!-- End Pagination -->

app/views/search/find_by_tag.html.erb
<%= render partial: 'search_bar', locals: {type: 'tag'} %>
<div clas="row">
  <div class="col-md-12">
    <h2>Recipe Search Result: tag <b>"<%= @keyword %>"</b></h2>
  </div>
  <hr class="medium" />
</div>
<%= render partial: 'search_result_table', locals: {items: @recipes, type: 'recipe'} %>
<!-- Begin Pagination -->
<div class="pagination-container text-center">
  <div class="row">
    <div class="col-md-12">
      <ul class="pagination pagination-sm works-pagination">
        <%= paginate @recipes %>
      </ul>
    </div>
  </div>
</div>
<!-- End Pagination -->

app/views/search/find_by_user.html.erb
<%= render partial: 'search_bar', locals: {type: 'user'} %>
<div clas="row">
  <div class="col-md-12">
    <h2>User Search Result: <b>"<%= @keyword %>"</b></h2>
  </div>
  <hr class="medium" />
</div>
<%= render partial: 'search_result_table', locals: {items: @users, type: 'user'} %>
<!-- Begin Pagination -->
<div class="pagination-container text-center">
  <div class="row">
    <div class="col-md-12">
      <ul class="pagination pagination-sm works-pagination">
        <%= paginate @users %>
      </ul>
    </div>
  </div>
</div>
<!-- End Pagination -->

app/views/search/index.html.erb
<%= render partial: 'search_bar', locals: {type: 'recipe'} %>
<div clas="row">
  <div class="col-md-12">
    <h2>Search</h2>
  </div>
</div>