config/routes.rb
Rails.application.routes.draw do
  get 'homepage/show'
  get 'profile/:id', to: 'profile#show', as: :profile
  get 'search', to: 'search#index'
  get 'search/find_by_recipe', to: 'search#find_by_recipe', as: :search_find_by_recipe
  get 'search/find_by_tag', to: 'search#find_by_tag', as: :search_find_by_tag
  get 'search/find_by_user', to: 'search#find_by_user', as: :search_find_by_user
  resources :masterpieces
  resources :recipes
  resources :collections
  devise_for :users
  post '/recipes/:id/like', to: 'recipes#like', as: :recipe_like
  post '/recipes/:id/unlike', to: 'recipes#unlike', as: :recipe_unlike
  post '/recipes/:id/bookmark', to: 'recipes#bookmark', as: :recipe_bookmark
  post '/recipes/:id/unbookmark', to: 'recipes#unbookmark', as: :recipe_unbookmark
  post '/masterpieces/:id/like', to: 'masterpieces#like', as: :masterpiece_like
  post '/masterpieces/:id/unlike', to: 'masterpieces#unlike', as: :masterpiece_unlike
  root 'homepage#show'

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_server_error'
  get 'errors/security_transgression_error', as: :security_transgression_error

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :ingredients, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_many :masterpieces, dependent: :destroy
  has_many :cooks, through: :masterpieces, source: :cook
  has_many :user_like_recipes, dependent: :destroy
  has_many :users_liking_it, through: :user_like_recipes, source: :user
  has_many :user_bookmark_recipes, dependent: :destroy
  has_many :users_bookmarking_it, through: :user_bookmark_recipes, source: :user

  has_many :collection_recipes
  has_many :collections, through: :collection_recipes, source: :collection

  has_attached_file :recipe_img, styles: {
    thumb: '100x100#',
    square: '200x200#',
    medium: '300x300#',
    slide: '1120x400#'
  }, default_url: "/images/default/missing_:attachment_:style.jpg"
  acts_as_taggable_on :tags
  accepts_nested_attributes_for :ingredients, reject_if: lambda { |a| a[:name].blank?}, allow_destroy: true
  accepts_nested_attributes_for :steps, allow_destroy: true

  validates :creator, :title, presence: true
  validates_attachment_content_type :recipe_img, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.search(search)
     search_condition = "%"+search+"%"
     where("title LIKE ? OR description LIKE ?  ",  search_condition, search_condition)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :tagged]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like, :unlike, :bookmark, :unbookmark]
  before_action :check_permission, only: [:edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @tags = @recipe.tags
    @ingredients = @recipe.ingredients
    @masterpieces = @recipe.masterpieces.includes(:cook)
    @steps = @recipe.steps
    @users_liking_it = @recipe.users_liking_it
    @users_bookmarking_it = @recipe.users_bookmarking_it
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    3.times{@recipe.ingredients.build}
    @recipe.steps.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    # if params[:add_ingredient]
    #   @recipe.ingredients.build
    # end
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    click_page = params[:click_page]
    notice = ""
    if @recipe.users_liking_it.include?(current_user)
      notice = "You've liked this recipe before."
    else
      @recipe.users_liking_it << [current_user]
      @recipe.save
    end
    respond_to do |format|
      if click_page == 'recipe_show'
        format.html { redirect_to @recipe, notice: "#{notice}" }
      end
    end
  end

def unlike
    click_page = params[:click_page]
    notice = ""
    if @recipe.users_liking_it.include?(current_user)
      @recipe.users_liking_it.destroy(current_user)
      @recipe.save
      notice = "You've liked it before."
    else
      notice = "You haven't liked it yet."
    end
    respond_to do |format|
      if click_page == 'recipe_show'
        format.html { redirect_to @recipe, notice: "#{notice}" }
      end
    end
  end

  def bookmark
    click_page = params[:click_page]
    notice = ""
    if @recipe.users_bookmarking_it.include?(current_user)
      notice = "You've bookmarked it before."
    else
      @recipe.users_bookmarking_it << [current_user]
      @recipe.save
    end
    respond_to do |format|
      if click_page == 'recipe_show'
        format.html { redirect_to @recipe, notice: "#{notice}" }
      end
    end
  end

   def unbookmark
    click_page = params[:click_page]
    notice = ""
    if @recipe.users_bookmarking_it.include?(current_user)
      @recipe.users_bookmarking_it.destroy(current_user)
      @recipe.save
      notice = "You've bookmarked it before."
    else
      notice = "You haven't bookmarked it yet."
    end
    respond_to do |format|
      if click_page == 'recipe_show'
        format.html { redirect_to @recipe, notice: "#{notice}" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:user_id, :title, :description, :cook_time, :recipe_img, :tag_list,
                                      ingredients_attributes: [:id, :recipe_id, :name, :quantity, :_destroy],
                                      steps_attributes: [:id, :recipe_id, :step_number, :description, :step_img, :_destroy])
    end

    def check_permission
      raise SecurityTransgression unless current_user == @recipe.creator
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  include ActsAsTaggableOn::TagsHelper
  def cache_key_for_masterpiece_snippet(masterpiece)
    "masterpiece-#{masterpiece.id}-#{masterpiece.updated_at.try(:utc).try(:to_s, :number)}"
  end

  # def cache_key_for_recipe_show_part1(recipe)
  #   "recipe-show-part1-#{recipe.id}-#{recipe.updated_at.try(:utc).try(:to_s, :number)}"
  # end
  #
  # def cache_key_for_recipe_show_part2(recipe)
  #   "recipe-show-part2-#{recipe.id}-#{recipe.updated_at.try(:utc).try(:to_s, :number)}"
  # end
end

app/views/recipes/_form.html.erb
<%= simple_nested_form_for(@recipe, multipart: true) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.hidden_field :user_id, value: current_user.id %>

<div class="field">

  <%= f.input :title, label: 'Recipe Title', placeholder: 'Enter recipe title' %>
  <%= f.input :tag_list, label: 'Tag', placeholder: 'Enter tags(separated by comma)' , input_html: { value: @recipe.tag_list.join(", ") }%>
  <%= f.input :description, label: 'Description', placeholder: 'Enter recipe description' %>
  <%= f.input :cook_time, label: 'Cook Time(in min)', placeholder: 'Enter cook time in minute' %>
</div>

<div class="field">
  <%= f.label 'Ingredients' %>
  <%= f.simple_fields_for :ingredients do |i| %>
    <div class="input-group">
      <%= i.input :name, label: false, required: false, placeholder: 'Enter ingredient\'s name' %>
      <span class="input-group-btn" style="width:0px;"></span>
      <%= i.input :quantity, label: false, required: false, placeholder: 'Enter quantity' %>
      <span class="input-group-btn">
        <%= i.link_to_remove "<span class='glyphicon glyphicon-remove'></span>".html_safe, class:'btn btn-default' %>
      </span>
    </div>
  <% end %>
<%= f.link_to_add "<span class='glyphicon glyphicon-plus'></span> Add".html_safe, :ingredients, class:'btn btn-default' %>
</div>

<div class="field">
  <%= f.label 'Steps' %>
  <%= f.simple_fields_for :steps do |s| %>
    <div class="row">
      <%= s.input :step_number, label: false, required: false, placeholder: 'Enter step number', wrapper_html: { class: 'col-md-1' }, input_html: { style: 'height: 150px;' } %>
      <%= s.input :description, label: false, required: false, placeholder: 'Enter step description', wrapper_html: { class: 'col-md-8' }, input_html: { style: 'height: 150px;' } %>
      <%= s.input :step_img, as: :step_img, label: false, wrapper_html: { class: 'col-md-2' } %>
      <%= s.link_to_remove "<span class='glyphicon glyphicon-remove'></span>".html_safe, class:'btn btn-default' %>
    </div>
  <% end %>
<%= f.link_to_add "<span class='glyphicon glyphicon-plus'></span> Add".html_safe, :steps, class:'btn btn-default' %>
</div>

<%= f.input :recipe_img, as: :recipe_img, label:'Recipe Picture' %>

<div class="action">
  <%= f.button :submit %>
</div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe, class: "btn btn-default" %>
<%= link_to 'Cancel', root_path, class: "btn btn-default" %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Cook time</th>
      <th>Steps</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.creator.email %></td>
        <td><%= recipe.title %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.cook_time %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%= image_tag recipe.recipe_img.url(:square) %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<% cache('recipe-new') do %>
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Cancel', root_path, class: "btn btn-default" %>
<% end %>

app/views/recipes/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="row">
  <div class="col-sm-12">
    <h3><%= @recipe.title %></h3>
    <p>Tags:
    <% @tags.each do |tag| %>
      <span class="tag-link"><%= link_to tag.name, search_find_by_tag_path(search: tag.name), class: "btn btn-custom light-gray" %></span>
    <% end %>
    </p>
  </div>
</div>
<div class="row">
  <%= image_tag @recipe.recipe_img.url, class: "col-md-8 img-responsive"%>

  <div class="col-md-4">
    <p><%= image_tag @recipe.creator.avatar.url(:thumb)%></p>
    <p>Created by: <span class="user-link"><%= link_to @recipe.creator.username, profile_path(@recipe.creator) %></span></p>
    <% if user_signed_in? %>
      <% if @users_liking_it.select{|t| t.id == current_user.id}.present? %>
        <div id="unlike-recipe-form">
        <%= button_to recipe_unlike_path(@recipe), class: "btn btn-danger", params: {click_page: 'recipe_show'} do %>
          <span class="glyphicon glyphicon-heart"></span> unlike
        <% end %>
        </div>
      <% else %>
        <div id="like-recipe-form">
        <%= button_to recipe_like_path(@recipe), class: "btn btn-default", params: {click_page: 'recipe_show'} do %>
          <span class="glyphicon glyphicon-heart"></span> like
        <% end %>
        </div>
      <% end %>
      <% if @users_bookmarking_it.select{|t| t.id == current_user.id}.present? %>
        <div id="unbookmark-recipe-form">
        <%= button_to recipe_unbookmark_path(@recipe), class: "btn btn-warning", params: {click_page: 'recipe_show'} do %>
          <span class="glyphicon glyphicon-bookmark"></span> unbookmark
        <% end %>
        </div>
      <% else %>
        <div id="bookmark-recipe-form">
        <%= button_to recipe_bookmark_path(@recipe), class: "btn btn-default", params: {click_page: 'recipe_show'} do %>
          <span class="glyphicon glyphicon-bookmark"></span> bookmark
        <% end %>
        </div>
      <% end %>
    <% else %>
        <%= button_to recipe_like_path(@recipe), class: "btn btn-default", disabled: true, params: {click_page: 'recipe_show'} do %>
          <span class="glyphicon glyphicon-heart"></span> like
        <% end %>
        <%= button_to recipe_bookmark_path(@recipe), class: "btn btn-default", disabled: true, params: {click_page: 'recipe_show'} do %>
          <span class="glyphicon glyphicon-bookmark"></span> bookmark
        <% end %>
    <% end %>

    <p><span class="count-number"><%= @users_liking_it.length %></span> people liked it</p>
    <p>
      <% @users_liking_it.each do |user| %>
        <%= image_tag user.avatar.url(:tiny)%>
      <% end %>
    </p>
    <p><span class="count-number"><%= @users_bookmarking_it.length %></span> people bookmarked it</p>
    <p>
      <% @users_bookmarking_it.each do |user| %>
        <%= image_tag user.avatar.url(:tiny)%>
      <% end %>
    </p>
    <p><span class="count-number"><%= @masterpieces.length %></span> people cooked it</p>

  </div>
</div>

<h3>Description:</h3>
<p>
  <%= @recipe.description %>
</p>


<h3>Ingredients:</h3>
<p>
  <% @ingredients.each do |ingredient| %>
    <p>
      <%= ingredient.name %>
      <%= ingredient.quantity %>
    </p>
  <% end %>
</p>

<h3>Cook time:</h3>
<p>
  <%= @recipe.cook_time %> min
</p>

<h3>Steps:</h3>
<p>
  <% @steps.each do |step| %>
    <p>
      <%= image_tag step.step_img.url(:square)%>
      <span class="step-number"><%= step.step_number %></span>
      <%= step.description %>
    </p>
  <% end %>
</p>


<h3>Masterpieces:</h3>
<div class="works">
  <div class="row">
    <% @masterpieces.each do |masterpiece| %>
      <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
        <div class="work-item">
          <%= image_tag masterpiece.masterpiece_img.url(:square) %>
          <!-- <img src="images/works/thumbs/1.jpg" alt=""> -->
          <div class="item-info">
            <div>
              <h4><%= masterpiece.cook.email %></h4>
              <p>
                <%= masterpiece.description%>
              </p>
              <ul class="item-options">
                <li><span class="masterpiece-modal-link"><a class="enlarge" data-toggle="modal" href="#modal<%= masterpiece.id %>"></a></span></li>
                <li><span class="masterpiece-link"><a class="view slower" href="<%= masterpiece_path(masterpiece) %>"></a></span></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Modal -->
        <div class="modal custom-modal fade" id="modal<%= masterpiece.id %>" tabindex="-1" role="dialog" aria-labelledby="modal<%= masterpiece.id %>" aria-hidden="true">
          <div class="modal-dialog" >
            <%= image_tag(masterpiece.masterpiece_img.url)%>
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
      </div>
    <% end %>
  </div>
</div>


<% if current_user != nil %>
  <%= link_to "Upload new masterpiece", {controller: 'masterpieces', action: 'new', masterpiece: {recipe_id: @recipe.id}}, class: "btn btn-default"%>
<% end %>

<% if current_user == @recipe.creator%>
  <%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn btn-default" %>
<% end %>

<% if current_user == @recipe.creator%>
  <%= link_to 'Delete this recipe', @recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
<% end %>

<!-- <%= params.inspect %> -->