config/routes.rb
Rails.application.routes.draw do
  get 'homepage/show'
  get 'profile/:id', to: 'profile#show', as: :profile
  get 'search', to: 'search#index'
  get 'search/find_by_recipe', to: 'search#find_by_recipe', as: :search_find_by_recipe
  get 'search/find_by_tag', to: 'search#find_by_tag', as: :search_find_by_tag
  get 'search/find_by_user', to: 'search#find_by_user', as: :search_find_by_user
  resources :masterpieces
  resources :recipes
  resources :collections
  devise_for :users
  post '/recipes/:id/like', to: 'recipes#like', as: :recipe_like
  post '/recipes/:id/unlike', to: 'recipes#unlike', as: :recipe_unlike
  post '/recipes/:id/bookmark', to: 'recipes#bookmark', as: :recipe_bookmark
  post '/recipes/:id/unbookmark', to: 'recipes#unbookmark', as: :recipe_unbookmark
  post '/masterpieces/:id/like', to: 'masterpieces#like', as: :masterpiece_like
  post '/masterpieces/:id/unlike', to: 'masterpieces#unlike', as: :masterpiece_unlike
  root 'homepage#show'

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_server_error'
  get 'errors/security_transgression_error', as: :security_transgression_error

end

app/models/masterpiece.rb
class Masterpiece < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :cook, foreign_key: 'user_id', class_name: 'User'
  has_many :user_like_masterpieces, dependent: :destroy
  has_many :users_liking_it, through: :user_like_masterpieces, source: :user
  has_attached_file :masterpiece_img, styles: {
    thumb: '100x100#',
    square: '200x200#',
    medium: '300x300#'
  }, default_url: "/images/default/missing_:attachment_:style.jpg"
  validates :recipe, :cook, presence: true
  validates_attachment_content_type :masterpiece_img, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/masterpieces_controller.rb
class MasterpiecesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_masterpiece, only: [:edit, :update, :destroy, :like, :unlike]
  before_action :check_permission, only: [:edit, :update, :destroy]

  # GET /masterpieces
  # GET /masterpieces.json
  def index
    @masterpieces = Masterpiece.all
  end

  # GET /masterpieces/1
  # GET /masterpieces/1.json
  def show
    @masterpiece = Masterpiece.select('id, description, user_id, recipe_id, masterpiece_img_file_name').find(params[:id])
  end

  # GET /masterpieces/new
  def new
    @masterpiece = Masterpiece.new
    @recipe_id = masterpiece_params[:recipe_id]
    @user_id = current_user.id if current_user
  end

  # GET /masterpieces/1/edit
  def edit
    @recipe_id = @masterpiece.recipe.id
    @user_id = @masterpiece.cook.id
  end

  # POST /masterpieces
  # POST /masterpieces.json
  def create
    @masterpiece = Masterpiece.new(masterpiece_params)

    respond_to do |format|
      if @masterpiece.save
        format.html { redirect_to @masterpiece, notice: 'Masterpiece was successfully created.' }
        format.json { render :show, status: :created, location: @masterpiece }
      else
        format.html { render :new }
        format.json { render json: @masterpiece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masterpieces/1
  # PATCH/PUT /masterpieces/1.json
  def update
    respond_to do |format|
      if @masterpiece.update(masterpiece_params)
        format.html { redirect_to @masterpiece, notice: 'Masterpiece was successfully updated.' }
        format.json { render :show, status: :ok, location: @masterpiece }
      else
        format.html { render :edit }
        format.json { render json: @masterpiece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masterpieces/1
  # DELETE /masterpieces/1.json
  def destroy
    @masterpiece.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Masterpiece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    click_page = params[:click_page]
    notice = ""
    if @masterpiece.users_liking_it.include?(current_user)
      notice = "You've liked this masterpiece before."
    else
      @masterpiece.users_liking_it << [current_user]
      @masterpiece.save
    end
    respond_to do |format|
      if click_page == 'masterpiece_show'
        format.html { redirect_to @masterpiece, notice: "#{notice}" }
      end
    end
  end

 def unlike
    click_page = params[:click_page]
    notice = ""
    if @masterpiece.users_liking_it.include?(current_user)
      @masterpiece.users_liking_it.destroy(current_user)
      @masterpiece.save
      notice = "You've liked it before."
    else
      notice = "You haven't liked it yet."
    end
    respond_to do |format|
      if click_page == 'masterpiece_show'
        format.html { redirect_to @masterpiece, notice: "#{notice}" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_masterpiece
      @masterpiece = Masterpiece.find(params[:id])
    end

    def check_permission
      raise SecurityTransgression unless current_user == @masterpiece.cook
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def masterpiece_params
      params.require(:masterpiece).permit(:recipe_id, :user_id, :description, :masterpiece_img)
    end
end

app/helpers/masterpieces_helper.rb
module MasterpiecesHelper
  def cache_key_for_masterpiece_show(masterpiece)
    max_users_liking_it_update = masterpiece.users_liking_it.max_by(&:updated_at).updated_at.try(:utc).try(:to_s, :number)
    "masterpiece-show-#{masterpiece.id}-#{masterpiece.updated_at.try(:utc).try(:to_s, :number)}-#{masterpiece.recipe.updated_at.try(:utc).try(:to_s, :number)}-#{current_user.id if current_user}-#{max_users_liking_it_update}"
  end
end

app/views/masterpieces/_form.html.erb
<%= simple_nested_form_for(@masterpiece, multipart: true) do |f| %>
  <% if @masterpiece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@masterpiece.errors.count, "error") %> prohibited this masterpiece from being saved:</h2>

      <ul>
      <% @masterpiece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.hidden_field :recipe_id, value: @recipe_id %>
    <%= f.hidden_field :user_id, value: @user_id %>
  </div>
  <div class="field">
    <%= f.input :description, label: 'Description', placeholder: 'Enter masterpiece description', input_html: { rows: 8 } %>
  </div>
  <div class="field">
    <%= f.input :masterpiece_img, as: :masterpiece_img, label:'Masterpiece Picture' %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-warning "%>
  </div>
<% end %>

app/views/masterpieces/edit.html.erb
<h1>Editing Masterpiece</h1>

<%= render 'form' %>

<%= link_to 'Show', @masterpiece, class: "btn btn-default" %>
<%= link_to 'Cancel', root_path, class: "btn btn-default" %>

app/views/masterpieces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Masterpieces</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>User</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @masterpieces.each do |masterpiece| %>
      <tr>
        <td><%= masterpiece.recipe.title %></td>
        <td><%= masterpiece.cook.email %></td>
        <td><%= masterpiece.description %></td>
        <%= image_tag masterpiece.masterpiece_img.url(:square) %>
        <td><%= link_to 'Show', masterpiece %></td>
        <td><%= link_to 'Edit', edit_masterpiece_path(masterpiece) %></td>
        <td><%= link_to 'Destroy', masterpiece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/masterpieces/new.html.erb
<% cache('masterpiece-new') do %>
<h1>New Masterpiece</h1>

<%= render 'form' %>

<%= link_to 'Cancel', root_path, class: "btn btn-default" %>
<% end %>

app/views/masterpieces/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Masterpiece - <%= @masterpiece.recipe.title %></h3>
<%= image_tag @masterpiece.masterpiece_img.url, class: "img-responsive"%>

<p><%= image_tag @masterpiece.cook.avatar.url(:thumb)%></p>
<p>Cooked by: <span class="user-link"><%= link_to @masterpiece.cook.username, profile_path(@masterpiece.cook) %></span></p>

<% if user_signed_in? %>
  <% if @masterpiece.users_liking_it.include?(current_user) %>
    <div id="unlike-masterpiece-form">
    <%= button_to masterpiece_unlike_path(@masterpiece), class: "btn btn-danger", params: {click_page: 'masterpiece_show'} do %>
      <span class="glyphicon glyphicon-heart"></span> unlike
    <% end %>
    </div>
  <% else %>
    <div id="like-masterpiece-form">
    <%= button_to masterpiece_like_path(@masterpiece), class: "btn btn-default", params: {click_page: 'masterpiece_show'} do %>
      <span class="glyphicon glyphicon-heart"></span> like
    <% end %>
    </div>
  <% end %>
<% else %>
    <%= button_to masterpiece_like_path(@masterpiece), class: "btn btn-default", disabled: true, params: {click_page: 'masterpiece_show'} do %>
      <span class="glyphicon glyphicon-heart"></span> like
    <% end %>
<% end %>

<p>
  <span class="count-number"><%= @masterpiece.users_liking_it.length %></span> people liked it
</p>
<p>
  <% @masterpiece.users_liking_it.each do |user| %>
    <%= image_tag user.avatar.url(:tiny)%>
  <% end %>
</p>

<h3>Description:</h3>
<p>
  <%= @masterpiece.description %>
</p>

<h3>Parent Recipe:</h3>
<p>
  <%= image_tag @masterpiece.recipe.recipe_img.url(:thumb)%>
  <span class="recipe-link"><%= link_to @masterpiece.recipe.title , @masterpiece.recipe %></span>
</p>

<% if current_user == @masterpiece.cook%>
  <%= link_to 'Edit', edit_masterpiece_path(@masterpiece), class: "btn btn-default" %>
<% end %>

<% if current_user == @masterpiece.cook%>
  <%= link_to 'Destroy', @masterpiece, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"%>
<% end %>